server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: document-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/documents/**

        - id: versioning-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/versions/**

        - id: comment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/comments/**

        - id: collaboration-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/collab/**

        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/notify/**

        - id: storage-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/storage/**

        - id: cad-api-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/cad/**

        - id: plm-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/plm/**
