server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collaborationdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

jwt:
  secret: secret-key-for-jwt
