server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plmdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

document-service:
  url: http://localhost:8082

notification-service:
  url: http://localhost:8087
